apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    workload.user.cattle.io/workloadselector: deployment-als-portal-web
  name: web
  namespace: als-portal
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-als-portal-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-als-portal-web
    spec:
      containers:
        - env:
          - name: env
            value: als-prod
          image: ghcr.io/scicatproject/frontend:4f57ad8ffb5377f92af23de47f73640d0c7eb129
          imagePullPolicy: Always
          name: web
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
              - NET_BIND_SERVICE
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 79966
          stdin: true
          tty: true
          volumeMounts:
          # - mountPath: /etc/nginx/nginx.conf
          #   name: catanie-nginx-vol
          #   readOnly: true
          #   subPath: nginx.conf
          # - mountPath: /usr/share/nginx/html/assets/config.json
          #   name: catanie-config-vol
          #   readOnly: true
          #   subPath: config.json
          - name: als-settings
            readOnly: true
            mountPath: /etc/nginx/nginx.conf
            subPath: als-settings/frontend/nginx/nginx.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always          
      initContainers:
        # A sidecar container that downloads current main from setttings github repo
        # and places it into an emptydir volume. This gets picked up by scicat backend
        # which mountains files 
        - name: git-sync
          image: k8s.gcr.io/git-sync:v3.1.6
          env:
            - name: GIT_SYNC_REPO
              value: "https://github.com/als-computing/scicat_als_config.git"
            - name: GIT_SYNC_BRANCH
              value: "main"
            - name: GIT_SYNC_ROOT
              value: "/als-settings"
            - name: GIT_SYNC_DEST
              value: "als-settings"
            - name: GIT_SYNC_ONE_TIME
              value: "true"
          volumeMounts:
            - name: als-settings
              readOnly: false
              mountPath: /als-settings
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
              - NET_BIND_SERVICE
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 79966
      securityContext:
        fsGroup: 94721
      volumes:
        - name: als-settings
          emptyDir:
        # - configMap:
        #     defaultMode: 256
        #     name: catanie-nginx
        #     optional: false
        #   name: catanie-nginx-vol
        # - configMap:
        #     defaultMode: 292
        #     items:
        #       - key: config.json
        #         mode: 292
        #         path: config.json
        #     name: catanie-config
        #     optional: false
        #   name: catanie-config-vol